### ISSUE TITLE
:bug:社区 清除选择按钮无效

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1110]
![企业微信截图_20230411135157](https://user-images.githubusercontent.com/117618324/231068474-1c23508f-027c-40eb-8737-654ca77764d9.png)

**Comment by ariyamaggika** [comment]
测试未修复

**Comment by visuddhinanda** [comment]
改好了

**Comment by ariyamaggika** [comment]
测试已修复
