### ISSUE TITLE
社区字典排序优化

### ISSUE THREAD

**Issue by visuddhinanda** [iapt-platform/mint#1120]
![6F71A52D-D825-4259-A4A0-FF9CE683DE63.png](https://user-images.githubusercontent.com/63999293/232313084-03d1a749-c872-49c7-bd7e-dc43d3d51c80.png)

http://visuddhinanda.spring.wikipali.org:60080/my/dict/va%E1%B9%87%E1%B9%87an%C4%81

在字典栏目加了社区字典。目前的结果是按照分数排序的。分数过低的会显示在弹出气泡中。蓝色的是分数。这个是计算分的代码

https://github.com/visuddhinanda/mint/blob/agile/dashboard/src/components/dict/Community.tsx#L48-L48

需要 @bhikkhu-kosalla-china 帮忙优化排序公式。

目前的算法
1，获取某单词的全部用户字典数据。
2，数据包涵用户提交数据时的经验值（秒），该记录的用户认为的信心指数（0-100）
3，遍历每条记录。将同样的数据（比如一样的意思）计算分数并相加。
4，分数：经验值（小时）×信心指数/100
5，小于100分默认不展示。（仅仅由单个的100小时以下经验值用户的数据）

**Comment by bhikkhu-kosalla-china** [comment]
升级算法
1. 获取某单词的全部用户字典数据。
2. 数据包涵用户提交数据时的经验值（秒），该记录的用户认为的信心指数（0-5）
3. 遍历每条记录。将同样的数据（比如一样的意思）计算分数并相加。
4. 分数=经验值（小时）×信心指数/5（）
5. 默认不展示的条件(词条)
    - 默认参数：标准得分Ms=500，默认展示条数Rd=5条，得分底线Min=15，若实际排名≤5，则展示，实际排名＞5，不展示
    - 设实际排名为Rr，经验值小时数Exp，信心指数Co，if满足下面的条件

$R_r > Lg(Exp \times Co/5) \div Lg(M_s^{1/R_d})$

或
$(Exp \times Co/5) < Min$

则不展示，else展示。

此算法可以保证在数据较少的时候，得分偏低的也能，不比一刀切
