### ISSUE TITLE
:bug:群组 点击编辑第一次显示默认信息不是当前群组

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1122]
点击编辑第一次显示默认信息不是当前群组，是上一个群组的信息

https://user-images.githubusercontent.com/117618324/236098400-6c9c021e-56ef-401e-bb17-6c6537038c08.mp4

**Comment by ariyamaggika** [comment]
测试未修复

**Comment by visuddhinanda** [comment]
这个不好改。查不出bug的原因。也没有报错信息。临时改为点编辑按钮弹新标签页。可以用。

**Comment by ariyamaggika** [comment]
测试已修复
