### ISSUE TITLE
:bug:文集(studio) 修改信息 无法添加目录

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1130]
https://github.com/iapt-platform/mint/assets/117618324/e1ebae7d-759a-4e06-9acf-baf498c6c677

**Comment by ariyamaggika** [comment]
测试未修复

https://github.com/iapt-platform/mint/assets/117618324/24d8be49-f300-43f3-b09c-c9c1e548f895

**Comment by visuddhinanda** [comment]
这个不能用多选。只能点标题。回头我把多选去掉。

**Comment by visuddhinanda** [comment]
已经修改。禁用多选。

**Comment by ariyamaggika** [comment]
测试已修复
