### ISSUE TITLE
:bug:术语(studio)  中文环境下 导入导出按钮与弹窗显示是英文

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1138]
![图片](https://github.com/iapt-platform/mint/assets/117618324/07a3ddf0-e3c7-4e39-b027-5684171a5dd5)
![图片](https://github.com/iapt-platform/mint/assets/117618324/db356e11-4e92-4b74-aa7b-e6fa2f119440)

**Comment by ariyamaggika** [comment]
测试未修复

**Comment by visuddhinanda** [comment]
已修改

**Comment by ariyamaggika** [comment]
测试已修复
