### ISSUE TITLE
:bug:术语(studio)  导出的结果不是选择的术语而是本地创建的术语

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1139]
https://github.com/iapt-platform/mint/assets/117618324/96d844ab-458a-49ea-90c0-e624ff107f1e

不知道是特性还是bug

**Comment by visuddhinanda** [comment]
目前批量操作只支持删除。不支持导出。也就是说，导出只支持全部导出，不支持局部导出。
