### ISSUE TITLE
:bug:翻译界面 保存快捷键无效&保存后输入框不消失

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1144]
![图片](https://github.com/iapt-platform/mint/assets/117618324/2681a226-6960-4501-9008-4104704a4193)

https://github.com/iapt-platform/mint/assets/117618324/de569f7a-499f-4f9d-af14-332bfc3d2682

**Comment by ariyamaggika** [comment]
测试未修复

**Comment by visuddhinanda** [comment]
已经修复
