### ISSUE TITLE
:bug:翻译界面 原文按钮点不动

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1147]
https://github.com/iapt-platform/mint/assets/117618324/e7b6a4cc-0491-439e-98f0-1790133406d4

**Comment by visuddhinanda** [comment]
这个是antd的问题。disabled按钮没有变成灰色。暂时去掉这个按钮吧。

**Comment by ariyamaggika** [comment]
![图片](https://github.com/iapt-platform/mint/assets/117618324/042130f0-59f8-4f39-9097-4325d92cb95b)
按钮还在

**Comment by visuddhinanda** [comment]
已经隐藏
