### ISSUE TITLE
:bug:逐词解析 讨论导航 没数据

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1152]
https://github.com/iapt-platform/mint/assets/117618324/ecd1bbc2-efff-4789-a372-a28baef7ad78

**Comment by ariyamaggika** [comment]
测试未修复
没有显示讨论
![图片](https://github.com/iapt-platform/mint/assets/117618324/917cd446-3955-48e6-a09e-858000e86ca1)

![图片](https://github.com/iapt-platform/mint/assets/117618324/a2c7de52-f097-4697-bb9e-1e10123ebd9d)

**Comment by visuddhinanda** [comment]
目前只支持句子讨论的列表

**Comment by ariyamaggika** [comment]
![图片](https://github.com/iapt-platform/mint/assets/117618324/2e50bb11-072c-4619-8455-4084bf85c31d)

**Comment by ariyamaggika** [comment]
测试已修复
