### ISSUE TITLE
翻译界面 点词查询断句错误

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1161]
https://github.com/iapt-platform/mint/assets/84234053/f44ac3fe-1cb4-416d-adc0-b3f54a2b7248

带有标点符号的词，在点词的时候有问题

**Comment by visuddhinanda** [comment]
已经修复

测试地址

http://visuddhinanda.spring.wikipali.org:60080/my/article/chapter/140-526

![image](https://github.com/iapt-platform/mint/assets/63999293/af04729f-dda7-4ad3-9cdb-04a22c23515d)

**Comment by visuddhinanda** [comment]
已经修复
