### ISSUE TITLE
🐛 逐词译乱码

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1169]
[问题地址](https://www-hk.wikipali.org/app/studio/editor.php?op=opendb&doc_id=93dabb70-1475-43ed-b67b-8078482082e5)
![image](https://github.com/iapt-platform/mint/assets/84234053/3345aac1-5f71-42dc-9d99-cc9fb2285f06)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/4b0185f2-81a9-4b0b-81f7-698a1e3965c5)
