### ISSUE TITLE
🐛 群组搜索不到用户列表

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1170]
![image](https://github.com/iapt-platform/mint/assets/84234053/17993782-f6e0-4dfe-b30d-c92ec9bf770a)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/53d2dda0-6b24-442f-9bea-c1fc350e9aef)
