### ISSUE TITLE
讨论功能的使用问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1185]
![image](https://github.com/iapt-platform/mint/assets/84234053/7e30cdd5-324f-419b-9466-27e543ed6c3c)

在提问的时候无法提取原文和译文中的内容，可能的解决方案
![image](https://github.com/iapt-platform/mint/assets/84234053/e40d673e-cb38-4e7f-acdd-529a9a913ea1)
在这个区域显示该句子块的内容

**Comment by visuddhinanda** [comment]
已经解决

![image](https://github.com/iapt-platform/mint/assets/63999293/397cdd39-dbc5-4a54-a23c-797308024379)
