### ISSUE TITLE
channel的优先问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1196]
## 问题描述
当用户选择了某个channel后，展开注疏。里面显示的译文channel为注疏Channel。

![image](https://github.com/iapt-platform/mint/assets/84234053/fe5608b8-ffaa-44e8-a839-a9696aaa5f9a)

![image](https://github.com/iapt-platform/mint/assets/84234053/d15aa1a7-12e4-4655-8d66-648b5e77f887)

## 希望的效果
通常用户展开注疏的时候，会想要翻译相关注释。所以，默认加载与原文一致的channel比较方便工作。
>无论是否有选择channel，展开译文应该跟随默认channel的语言，且前后具有一致性

## 问题链接

[问题链接](https://next.wikipali.org/pcd/article/article/09b50293-260d-4b63-aeb6-5509903fcc3e?mode=edit&channel=41612a55-a8a6-4724-921f-bf0dcc319f89)

**Comment by bhikkhu-kosalla-china** [comment]
注疏的channel展示优先级
- 读者手动选择某channel
- 同语言&&有译文
   - 属于该channel拥有者&&最新
   - 属于该channel拥有者所在群组&&最新
   - 被该channel拥有者上传&&最新
   - 属于读者&&最新
   - 被读者上传&&最新
   - 被该channel拥有者所在群组成员上传&&最新
   - 全网默认的根据偏好的最高评价
- 读者第二语言&&有译文
   - 属于该channel拥有者&&最新
   - 属于该channel拥有者所在群组&&最新
   - 被该channel拥有者上传&&最新
   - 属于读者&&最新
   - 被读者上传&&最新
   - 被该channel拥有者所在群组成员上传&&最新
   - 全网默认的根据偏好的最高评价

如果读者的语言偏好列表中不存在的语言，则不展示

**Comment by visuddhinanda** [comment]
已经修改

![image](https://github.com/iapt-platform/mint/assets/63999293/fc176f83-4692-4ac2-a382-ac64268ea15f)
