### ISSUE TITLE
版本风格中的用户列表需要依照某个顺序排序

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1216]
![image](https://github.com/iapt-platform/mint/assets/84234053/83451ce8-d974-4577-947f-a4d03bc834ca)
如果不依照某个顺序排序，则看起来会很头疼

**Comment by visuddhinanda** [comment]
已修改

![image](https://github.com/iapt-platform/mint/assets/63999293/0a000bc3-ddcf-4fa2-8dce-f18fc3ef24e9)
