### ISSUE TITLE
nissaya气泡内容显示规则

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1247]
![image](https://github.com/iapt-platform/mint/assets/84234053/5fd657fd-8532-4f38-9104-8f927aca474f)
由于细节条目过多，因此需要精简显示，需要额外在箭头右侧的目标节点，添加分类字段，以实现折叠

字段顺序调整与合并规则如下：

## 合并状态

本词特征 | 关系 | 目标词特征 | 含义 | 翻译建议 
-- | -- | -- | -- | --
工具格 |  SV<br>施动者 ➡ 动词 | 被动动词 | 被动语态中表示逻辑主语 | _被_`本词` `目标词`, |  

## 展开状态

本词特征 | 关系 | 目标词特征 | 含义 | 翻译建议 
-- | -- | -- | -- | --
工具格 |  SV<br>施动者 ➡ 动词 | `未来被动分词` | 被动语态中表示逻辑主语 | _被_`本词` `目标词`, |  
工具格 |  SV<br>施动者 ➡ 动词 | `过去分词` | 被动语态中表示逻辑主语 | _被_`本词` `目标词`, |  
工具格 |  SV<br>施动者 ➡ 动词 | `动词` `被动式` | 被动语态中表示逻辑主语 | _被_`本词` `目标词`, |  
工具格 |  SV<br>施动者 ➡ 动词 | `现在分词` `被动式` | 被动语态中表示逻辑主语 | _被_`本词` `目标词`, |

**Comment by visuddhinanda** [comment]
总结一下思路：
如果某个relation 的解释（含义），用法 在不同的情况下（箭头左，箭头右）是一样的。无需加分类标签。可以用 relation 自己的term 数据。
如果含义不同（比如CAU 来源格和工具格和连续体，解释不同）需要用分类加以区分。
