### ISSUE TITLE
关系图规则维护

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1269]
关系图规则中，箭头左右都需要可以选择**语法特征**或**拼写特征**。比如：工具格表示伴随关系，其伴随关系连词是有限的几种。
![image](https://github.com/iapt-platform/mint/assets/84234053/5337f84e-e744-4820-9915-31293cc2abed)
然后，在维护界面上，只能选择语法特征， 无法提供拼写特征。
![image](https://github.com/iapt-platform/mint/assets/84234053/7c416492-2a16-42c3-9233-f9dba73beac6)

**Comment by visuddhinanda** [comment]
已经修改
