### ISSUE TITLE
术语维护界面的设计问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1279]
## 点击后拼写没有继承术语拼写，容易出错
![image](https://github.com/iapt-platform/mint/assets/84234053/0e2e1ff4-7a30-467b-9e1c-d0ea717163fd)

## channel选择器的排序有问题
![image](https://github.com/iapt-platform/mint/assets/84234053/3565c177-0174-4f82-bcf5-7704ec26aec9)
比较合适的顺序：
- 本句channel
- 本句channel所在用户或群组
- 自己个人
- 用户最近常用的10个channel——依照上传频度排序
- 余下依照名称排序，不能依照时间或使用频度排序

**Comment by visuddhinanda** [comment]
>用户最近常用的10个channel——依照上传频度排序

@bhikkhu-kosalla-china 能不能给个排序公式

输入：channel，更新时间

**Comment by bhikkhu-kosalla-china** [comment]
1. 数组取前7天的数据
2. 更新时间2=更新时间-注册时间
3. 依照channel名词，对更新时间2进行分类汇总
4. 依照分类汇总降序排列，取前十

**Comment by visuddhinanda** [comment]
用户最近常用的10个channel——依照上传频度排序 另外写issuse。其他已经修改
