### ISSUE TITLE
讨论界面的需求

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1280]
讨论时候，句子块过窄，讨论时候多有不便。希望讨论区域能够有一个拓宽按钮。

![image](https://github.com/iapt-platform/mint/assets/84234053/f207d18d-3510-4c8b-892a-a5c3de1fd891)

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/d6b84afa-baa5-45eb-982c-bc70a1f80f56)

![image](https://github.com/iapt-platform/mint/assets/63999293/fb1062d6-b04c-4318-ac98-867462a9185c)
