### ISSUE TITLE
🐛 术语维护的

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1281]
不改channel，意思修改，提交报错
![image](https://github.com/iapt-platform/mint/assets/84234053/a4c94e42-3058-481f-856c-5acc7691e5aa)
改channel，意思修改，提交报错
![image](https://github.com/iapt-platform/mint/assets/84234053/850a4533-ebfd-4328-9b0e-858f1012d932)

注：以上两个channel不是本人的，第一个不确定是否有权限，第二个确定有编辑权限

**Comment by bhikkhu-kosalla-china** [comment]
注：channel不是本人，但拥有编辑权限

**Comment by visuddhinanda** [comment]
已经修复
