### ISSUE TITLE
🐛 术语弹窗发现有两个按钮不能用

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1282]
![image](https://github.com/iapt-platform/mint/assets/84234053/080e7702-d681-4f84-bb0d-b01745ecbd5d)

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/7c9dd91f-7f32-44df-aa1b-16528c04c2a3)

已经修复
