### ISSUE TITLE
译文迁移功能上的缺陷

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1283]
## 2.0版本
![image](https://github.com/iapt-platform/mint/assets/84234053/cabbd354-8796-4c3a-8485-0eb65bb009d2)
## 1.0版本
![image](https://github.com/iapt-platform/mint/assets/84234053/b4dee061-6449-4b32-ac5e-9ee82af96a41)

目前与1.0相比，缺了两个关键功能：

- [ ] 针对某句的选择或不选
- [ ] 文本比对后，根据修改时间，建议更新或不更新
- [ ] 1.0有巴利原文，2.0没有；巴利原文是选择和不选的重要依据

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/e692ec10-a911-401e-9686-94c57aa67475)
