### ISSUE TITLE
🐛 某个术语无法正常显示

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1286]
![image](https://github.com/iapt-platform/mint/assets/84234053/04861c3d-6b62-4a1a-902a-441e2d4f00f1)
![image](https://github.com/iapt-platform/mint/assets/84234053/c4d673bf-85dd-410b-95ec-b68aaabb6465)

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/3decde4d-d4ad-4645-b474-5f495e69cda1)

COC abl后面多了个空格
