### ISSUE TITLE
🐛 nissaya气泡折叠的缺陷

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1287]
![image](https://github.com/iapt-platform/mint/assets/84234053/247a96cd-ec9d-4db7-86b3-d8c6a07a24a4)
在关系不同的时候，不应折叠

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/5cd44408-ed14-4f2f-bd8e-2c4fda8c93be)
