### ISSUE TITLE
🐛 nissaya语法气泡显示内容与显示不一致

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1290]
显示
![image](https://github.com/iapt-platform/mint/assets/84234053/50e7846f-a215-46d3-af49-b97983e738af)
内容
![image](https://github.com/iapt-platform/mint/assets/84234053/e537f68a-1def-4aec-8dc7-012e09b9a754)
其中，*ti没有格位，被强行加上了格位

**Comment by bhikkhu-kosalla-china** [comment]
## 带方向的关系语法

|本词特征|关系|目标词特征|含义|翻译建议|
|-|-|-|-|-|
|`处格` `动词衍生词`|DEF|→`动词`|引导时间状语从句，表示目标动词与本词同时发生|当……时|
|`处格` `动词衍生词`|SV|←`名词` `处格`|时间状语从句中，同格位的名词作为改动词的主语||

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/235bb9fb-22c0-4eee-86fd-3f0ae0e7a19a)

已经修复
