### ISSUE TITLE
级联选择器的设计缺陷

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1297]
![image](https://github.com/iapt-platform/mint/assets/84234053/6a42eb81-f80b-44b4-bb8b-b1526beefef3)

在实际操作和教学的时候，单词查询和语尾查询是分两步走；但是级联选择器因为不选择完不能结束，因此学员无法完成阶段性操作

**Comment by visuddhinanda** [comment]
# 遇到的问题


# 希望的效果

**Comment by visuddhinanda** [comment]
>在实际操作和教学的时候，单词查询和语尾查询是分两步走；但是级联选择器因为不选择完不能结束，因此学员无法完成阶段性操作

**这个没看懂**

>单词查询和语尾查询是分两步走
这个是什么意思？

>因此学员无法完成阶段性操作
阶段性操作是什么意思

**Comment by bhikkhu-kosalla-china** [comment]
## 遇到的问题
名词的语法信息填写步骤如下
1. 查询到词典原型，查询词类和词性
2. 填写词类和词性，不填写数和格
> 该操作1.0可以保存或暂存，2.0不支持
3. 查询语尾，得到性数格
4. 填写性数格
> 因为2.0不支持第2步，所以需要此步骤也受到影响

## 希望的效果

支持1.0支持但2.0现在不支持的操作

**Comment by visuddhinanda** [comment]
>支持1.0支持但2.0现在不支持的操作

只能放弃级联选择

**Comment by visuddhinanda** [comment]
目前的级联选择的顺序是
词类 >词性>数>格

暂时记录只有一个办法：在每个层级下面加一个“待定”

优点：能够暂时停止
缺点：只能按照词类 >词性>数>格的顺序停止，不能跳过，比如词性待定，确定格。如果要想实现这个，就得用1.0的选择方式。1.0的方式的缺点是代码复杂很难维护。

需要评估“暂时记录”的必要性是不是很大。比如
1. 很多学生都有这个困难，短期记忆一个词困难
2. 后半段暂时选一个可能性是否可以接受。 如已经选了名词>阳性，后面的不确定。随便选一下。确定了再回来改，是否可以接受？

我需要评估，学生，老师能够忍耐的极限是什么？对于程序来说。不用级联选择器是很难忍的。如果用户更不能忍。那么只能是程序员忍了。但是很痛苦。

**Comment by visuddhinanda** [comment]
已经添加待定选项
