### ISSUE TITLE
🐛 术语提交上的bug

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1298]
![image](https://github.com/iapt-platform/mint/assets/84234053/4d970e7d-367f-422a-a7ef-ef79b3bfb190)

新建术语时候，这里语言选择为灰色，无法进行选择，且又是必选，导致无法提交。

**Comment by bhikkhu-kosalla-china** [comment]
![image](https://github.com/iapt-platform/mint/assets/84234053/3d59c43e-2ef7-449b-a253-c775a2b2b908)

术语的下拉菜单背景颜色过于诡异，无法正常使用

**Comment by visuddhinanda** [comment]
已经修复
