### ISSUE TITLE
nissaya气泡尺寸过大

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1299]
![image](https://github.com/iapt-platform/mint/assets/84234053/c8b9d566-5a54-4352-94df-8ca6475b4ab5)

[链接](https://next.wikipali.org/pcd/article/chapter/164-55?mode=edit&channel=d7567fa0-9ba4-4334-a61c-42aba58699f0)

**Comment by visuddhinanda** [comment]
已经修正
