### ISSUE TITLE
🐛 ariticle显示不正常

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1301]
[问题链接](https://next.wikipali.org/pcd/article/article/85671464-d295-411d-bbdf-fb4e414c337d?mode=read)

![image](https://github.com/iapt-platform/mint/assets/84234053/15e76369-2f4b-4dee-b203-7051c05d54bf)

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/1103ded5-7629-4bb1-9cdd-9f7e15337511)

问题的原因：
video 里面的 url 有一个&字符。不符合xml规范。所以，服务器无法解析。把这个字符去掉就好了。这个url需要更新。可以尝试用unicode 不用url编码 @bhikkhu-kosalla-china

**Comment by visuddhinanda** [comment]
url全部用26个英文字母比较好。能够避免url编码问题。

**Comment by visuddhinanda** [comment]
在html解析器里面上面那种写法是合法的。但是目前server渲染用的是xml解析器。原因是 php 的html解析器不支持自定义标签。
