### ISSUE TITLE
功能恢复-复制整段句子编号的功能

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1308]
1.0有复制整段句子编号的功能
2.0需要恢复该功能，不然注释书穿插工作量太大

**Comment by visuddhinanda** [comment]
已经修复

**Comment by bhikkhu-kosalla-china** [comment]
![image](https://github.com/iapt-platform/mint/assets/84234053/12be38c6-ff45-404b-b024-0a6083387aab)

在单段显示模式下依然尚未修复，而且在搜索结果、注释跳转、单句溯源中只提供了**单段显示**模式的结果

[问题链接](https://next.wikipali.org/pcd/article/para?book=67&par=462,463)

**Comment by bhikkhu-kosalla-china** [comment]
该功能的缺失对于研发者而言非常不方便

**Comment by visuddhinanda** [comment]
与 #1379 重复
