### ISSUE TITLE
🐛 更多译文的计算错误

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1313]
[链接](https://next.wikipali.org/pcd/article/chapter/168-474?mode=edit&channel=06415a88-f674-4f00-9bbc-110eddcd365a_ca69f92f-17ef-4664-9559-47fffd5869f2)
![image](https://github.com/iapt-platform/mint/assets/84234053/1b2f9c78-bc62-4db8-9ab0-c5707de6c34b)

更多译文的数量没有排除异选中的channel，导致该数据有很大的误导性。
而且，这里显示4，但展示了2个。

**Comment by visuddhinanda** [comment]
已经修改
