### ISSUE TITLE
无法在新标签中跳转

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1314]
https://github.com/iapt-platform/mint/assets/84234053/7a5a36d7-4092-42af-8ce0-b313e02cc58c

[页面链接](https://next.wikipali.org/pcd/article/chapter/65-936?mode=edit&book=134&par=372&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

在使用过程中，大部分需要页面跳转的情况都是要保留原始页面的。
因此，是否能够实现页面跳转以另开页面的方式进行？尤其是**非链接跳转**。
因为，有链接的跳转，可以通过配合键盘的`shift键`或`ctrl键`来实现，但是非链接的跳转是没办法实现的。

**Comment by visuddhinanda** [comment]
已经修正。
非链接都可以按ctl + 鼠标弹窗。用js实现。
发现还有哪个没实现的，报bug @bhikkhu-kosalla-china
