### ISSUE TITLE
🐛 译文显示有bug

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1317]
![image](https://github.com/iapt-platform/mint/assets/84234053/35f93eeb-54e0-4e4a-aeaf-9093cb427452)

在该译文中，修改之后，默认显示的`译文`并没有显示最新，但`上传者`和`修改时间`显示为最新。
而在展开更多译文的时候，`译文`显示为最新

另外，粗体的**和“可能存在冲突，且译文编辑界面没有预览

![image](https://github.com/iapt-platform/mint/assets/84234053/6e70e735-306e-4c72-9af9-8c4e178e39e1)

[页面链接](https://next.wikipali.org/pcd/article/para/67-910?mode=edit&book=67&par=910&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
下面的译文不应该出现跟上面的重复的channel。这个问题已经修复。

译文编辑界面，如果使用带有预览的markdown编辑器。术语输入提示就不能有了。二选一。 @bhikkhu-kosalla-china
