### ISSUE TITLE
🐛 关键词检索的显示问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1318]
![image](https://github.com/iapt-platform/mint/assets/84234053/66090563-e1b6-44ee-acc6-0756c12eefe0)

[问题链接](https://next.wikipali.org/pcd/search/key/cetopariya%C3%B1%C4%81%E1%B9%87a%E1%B9%83?match=similar)

关键词额外加了删除线

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/fe3a6c24-6bf7-4b63-af33-4e199804d6a6)
 
已经修复
