### ISSUE TITLE
🐛 关系术语维护出错

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1319]
![image](https://github.com/iapt-platform/mint/assets/84234053/709f383f-a935-426d-aefe-65e635f2b9ed)

原有的术语修改提交，报错

[问题链接](https://next.wikipali.org/pcd/admin/relation/list)

**Comment by visuddhinanda** [comment]
这个无法复现。我保存正常。请再试一下。
