### ISSUE TITLE
🐛 文章无法打开

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1320]
![image](https://github.com/iapt-platform/mint/assets/84234053/943e629d-474e-4f1b-8549-03df9a4afa80)

[问题链接](https://next.wikipali.org/pcd/article/article/3d07ca34-2eed-446c-8b33-9cce31ecb054?mode=read&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d)

这个影响初级班上课

**Comment by visuddhinanda** [comment]
bug 已经修复。但是有一个问题。我把原来的文章内容在新版里面复制粘贴一个新的文章就正常。用原来的文章打开无法正常显示。目前查不到原因。建议在2.0里面打开再保存一下试试。

[测试链接](https://next.wikipali.org/pcd/article/article/cc80f1ca-d207-4274-bf6e-c1cfa1ebdf27)

![image](https://github.com/iapt-platform/mint/assets/63999293/80f20b37-ca50-43ea-832d-71ec7aff9b10)
