### ISSUE TITLE
channel选择没有进行筛选

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1334]
https://github.com/iapt-platform/mint/assets/84234053/4420aa42-7b72-4e9d-a932-539c020afb68

## 目前的问题
如视频所示，我在译文处添加，显示了很多type不是译文的channel，寻找channel不容易操作；
## 希望的效果
在译文处点击加号，显示type是译文的channel或令译文channel排名靠前。

**Comment by visuddhinanda** [comment]
已经修改，请在staging测试 
https://staging.wikipali.org/pcd/article/chapter/107-2356?mode=edit&channel=7fea264d-7a26-40f8-bef7-bc95102760fb
