### ISSUE TITLE
🐛 路径无法显示

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1335]
某些特定编号的句子无法显示其路径

![image](https://github.com/iapt-platform/mint/assets/84234053/8cdceb09-d178-4eab-8f0e-24b5845b6f61)
[问题链接](https://next.wikipali.org/pcd/article/chapter/65-936?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

然而，如果把该句子的书号、段落号放在链接里面再打开，则可在标题位置显示正确的路径

[结果链接](https://next.wikipali.org/pcd/article/chapter/81-1522?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)
但句子编号的路径依然存在问题
![image](https://github.com/iapt-platform/mint/assets/84234053/45ed39f3-8e77-4422-9ba6-9038278fc299)

**Comment by visuddhinanda** [comment]
已经修复。[测试链接](https://staging.wikipali.org/pcd/article/chapter/81-1522?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

![image](https://github.com/iapt-platform/mint/assets/63999293/f275fa81-04d4-466a-ad51-d8f0a8385009)
