### ISSUE TITLE
🐛 提出讨论问题时看不到巴利原文

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1337]
![image](https://github.com/iapt-platform/mint/assets/84234053/8e5eae07-84f2-40b9-90f7-a4c8027edeb2)

## 目前的效果
如果能看到和复制巴利原文，则看不到讨论编辑框；如果看到讨论编辑框则无法看到巴利原文

## 需要的效果
能够一边看到并可以复制巴利原文，一边可以在讨论编辑框中写内容

**Comment by bhikkhu-kosalla-china** [comment]
![image](https://github.com/iapt-platform/mint/assets/84234053/2911a886-c0ff-46da-8974-75308dc8edb8)

**标题**的设定有些费解，不知道写啥……能否不写？

**Comment by visuddhinanda** [comment]
>标题的设定有些费解，不知道写啥……能否不写？

github就是这样的

![image](https://github.com/iapt-platform/mint/assets/63999293/7861f984-359b-425e-8edf-294e08598900)

**Comment by bhikkhu-kosalla-china** [comment]
github和我们的应用场景不一样，
github的issue是一定围绕某个主题展开的，是开启一个新的话题，因此必须有标题；

但是我们类似于回帖：
论坛回帖是已经有人发了帖子的情况下，有些人回帖，这个是不需要主题的，包括github中回帖也不需要主题。

您之前的设定没有资源不允许回复；这其实就是默认了主题就是围绕这句话展开的。
因此，这个时候标题并不是必须的。

**Comment by bhikkhu-kosalla-china** [comment]
从实际应用场景和需求的角度上来说，给内容打标签，要比写标题来得更实在。
这样来表明我的提问属于哪种类型、立场、语气等等：`nissaya求助`，`提问求助`，`审稿质疑挑战`，`请教问题`，`翻译提醒`，`不同意见`等等。

**Comment by bhikkhu-kosalla-china** [comment]
如果要填写标题，请帮忙指点一下，我的标题应该写什么？
![image](https://github.com/iapt-platform/mint/assets/84234053/bc3b171d-454d-4b77-ba06-fdbd3be07e9e)

**Comment by visuddhinanda** [comment]
![2023-08-19 124827_edit_366950267511841.png](https://github.com/iapt-platform/mint/assets/63999293/64bbcd7c-2a9c-4d4c-990f-b7783bbb9617)

**Comment by visuddhinanda** [comment]
作为提问来说，标题是必要的，描述不是必要的。问题本身足够简短。20个字就能表达清楚。只有标题就够了。
作为回答来说，描述是必要的，标题不是必要的。
区分标题和描述，能够让程序准确的识别重要的部分。比如在消息推送中，提问标题应该全部推送，因为标题是限制长度的，全推送没问题。描述只推前n个字。如果没有标题，就只能推前n个字。

**Comment by bhikkhu-kosalla-china** [comment]
能否规避一下这种思考？比如，让用户不用考虑写什么标题，直接就知道里面就写问题。
比如：把`标题`改为`问题`；把`描述`改为`补充`？这样，用户填写就不会迷惑了。

**Comment by bhikkhu-kosalla-china** [comment]
不然，用户就会疑惑，我提个问题为啥要写标题呢？

**Comment by bhikkhu-kosalla-china** [comment]
百度知道
![image](https://github.com/iapt-platform/mint/assets/84234053/6eb737a2-8bee-425b-9eb5-0d92a19521e4)

**Comment by bhikkhu-kosalla-china** [comment]
知乎
![image](https://github.com/iapt-platform/mint/assets/84234053/37a84c21-07a8-4147-a3b1-9da1f0820b8d)

**Comment by bhikkhu-kosalla-china** [comment]
如果必填的部分，也希望格子能够拉大拉宽一些，看起来像是给人提问题的样子。

**Comment by bhikkhu-kosalla-china** [comment]
quora的提问界面
![image](https://github.com/iapt-platform/mint/assets/84234053/6e7f9116-9f29-402b-aa1a-a824b66f4d5f)

**Comment by visuddhinanda** [comment]
quora的提问页面，是只包含标题的。也没有你说的markdown预览。标题支持markdown我还没见过。知乎，百度知道标题支持markdown吗？

**Comment by visuddhinanda** [comment]
GitHub issues也是标题和描述两个部分，标题必填，描述可选。而且标题不支持markdown，描述支持。

![Screenshot_20230819_140924.jpg](https://github.com/iapt-platform/mint/assets/63999293/d929267c-e51a-4f79-8420-eff8c3f6ea9c)

![Screenshot_20230819_140917.jpg](https://github.com/iapt-platform/mint/assets/63999293/16ba878c-94ab-4d9c-a181-70184359e2c8)

**Comment by bhikkhu-kosalla-china** [comment]
> GitHub issues也是标题和描述两个部分，标题必填，描述可选。而且标题不支持markdown，描述支持。
> 
> ![Screenshot_20230819_140924.jpg](https://user-images.githubusercontent.com/63999293/261785399-d929267c-e51a-4f79-8420-eff8c3f6ea9c.jpg)
> 
> ![Screenshot_20230819_140917.jpg](https://user-images.githubusercontent.com/63999293/261785482-16ba878c-94ab-4d9c-a181-70184359e2c8.jpg)

markdown没有代表性，我不想借鉴，也不想讨论

**Comment by bhikkhu-kosalla-china** [comment]
> quora的提问页面，是只包含标题的。也没有你说的markdown预览。标题支持markdown我还没见过。知乎，百度知道标题支持markdown吗？

这个关键是强调，不要用标题这样的字眼，因为几个提问题的网站都没有用到“标题”这个字眼

**Comment by bhikkhu-kosalla-china** [comment]
> quora的提问页面，是只包含标题的。也没有你说的markdown预览。标题支持markdown我还没见过。知乎，百度知道标题支持markdown吗？

主要是在细节编辑部分支持markdown会让人主次迷惑；

当然，译文编辑部分，需要markdown工具栏和预览

**Comment by bhikkhu-kosalla-china** [comment]
github的issue承担的职能，和我们的提问只能相似度比较低；
百度、知乎和quora与我们的功能需求相似度比较高；
因此，issue的设计我不想参考。
其中，知乎、quora只有一个输入框，够简单；或许我们也可以考虑只保留一个输入框，
因为一个输入框能够满足需求的情况下，第二个输入框就显得有些多余。

**Comment by bhikkhu-kosalla-china** [comment]
我们的提问，相比**发帖**更贴近**跟帖**，只需要一个输入框；
而github是**发帖**，一定不是**跟帖**，所以需要标题+输入框；
知乎和quora的提问是**发帖**，但同样只有一个输入框。

所以，综上我建议用一个输入框，另一个输入框甚至可以隐藏或折叠，有需要再展开填写。

**Comment by visuddhinanda** [comment]
![Screenshot_7.jpg](https://github.com/iapt-platform/mint/assets/63999293/48d235a5-6cf4-4327-823b-eda4b48b4019)

**Comment by bhikkhu-kosalla-china** [comment]
能测试吗？

**Comment by visuddhinanda** [comment]
还有一个一揽子解决方案
目前discussion 数据库可以涵盖pr的所有功能。把discussion 做成3种type

|type|标题(纯文本)|内容(markdown)|备注(纯文本)|
|- | -| -|-|
| pr | *不填* | **必填** | **必填**（修改原因）|
| 问答 | **必填** | 选填 | *不填* |
| 评论 | *不填* | **必填** | *不填* |

这是github discussion的功能
