### ISSUE TITLE
🐛 讨论界面nissaya气泡无法显示完整

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1338]
![image](https://github.com/iapt-platform/mint/assets/84234053/a7c51083-1d93-4f80-901e-6889f95668b1)

[问题链接](https://next.wikipali.org/pcd/article/chapter/98-2035?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

内容无法显示完整，且无法滚动，建议提升内容的紧凑度，并把宽度给予一定限制。

**Comment by visuddhinanda** [comment]
气泡限宽750  表格改为紧缩，添加新窗口打开按钮

![image](https://github.com/iapt-platform/mint/assets/63999293/3c188522-b637-4374-996e-e206f5f214b0)
