### ISSUE TITLE
🐛 xml解析错误

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1339]
[问题链接](https://next.wikipali.org/pcd/article/article/3ada3b2c-32e0-44ac-9fbf-99d6805ecd1e?mode=read&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d)

![image](https://github.com/iapt-platform/mint/assets/84234053/53bab694-0ccd-4deb-a5f3-3643dc4015a3)

**Comment by visuddhinanda** [comment]
这个很麻烦。一周之内无法解决。

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/0e8df4dc-ba5f-4a1f-9a18-93c8dabcd7ed)
