### ISSUE TITLE
🐛 无法选择公开channel

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1345]
![image](https://github.com/iapt-platform/mint/assets/84234053/2c4dd016-9e6d-4476-abe9-66761f35babe)

[问题链接](https://next.wikipali.org/pcd/article/article/09b50293-260d-4b63-aeb6-5509903fcc3e?mode=read&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d)

入口：文集进入

**Comment by visuddhinanda** [comment]
如果急用的话，可以先用这个菜单

![image](https://github.com/iapt-platform/mint/assets/63999293/1f920a41-5fc9-4a80-9ace-6fdb9261cf23)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/4dccb059-09bd-46cd-bc64-012702da9802)
