### ISSUE TITLE
🐛 词典图标

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1346]
![image](https://github.com/iapt-platform/mint/assets/84234053/91ddd549-5687-4052-b0fa-fa9a79306ed3)

有两个图标，不明确，容易混乱

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/8667d92d-7f01-420f-ac1f-55f981a92792)
