### ISSUE TITLE
🐛 显示改变图标没有在其他地方出现

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1348]
![image](https://github.com/iapt-platform/mint/assets/84234053/39ce5b86-6f1e-4b75-9151-ba5dc7bbb14d)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/ef7f9f0c-c1b7-42ba-8573-461705b59668)
