### ISSUE TITLE
🐛 目录无法显示具体位置

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1349]
## 遇到的问题
![企业微信截图_fa967a96-19f2-4cac-aad3-e5f753b89c7f](https://github.com/iapt-platform/mint/assets/84234053/b519ea4a-e269-41a5-b425-1baaaf546c60)

[问题链接](https://next.wikipali.org/pcd/article/chapter/64-191?mode=edit&channel=41612a55-a8a6-4724-921f-bf0dcc319f89)

2.0打开目录时无法显示具体所在的章节位置，

## 需要的效果
而1.0会显示具体位置

![企业微信截图_b7c0605c-125c-4e56-8301-2a6ffac27a4e](https://github.com/iapt-platform/mint/assets/84234053/7dbcb21e-1a38-4bd3-9246-065b221a0adc)

[1.0链接](https://www-hk.wikipali.org/app/article/index.php?view=chapter&book=207&par=541&channal=59b79c56-eda8-4c41-a8d0-8f44a5ebcf41,f2b00c68-c32d-44e4-b00a-4e996915a65e&display=sent&mode=edit&direction=row)

**Comment by bhikkhu-kosalla-china** [comment]
以上反馈来自wikipāli学员

**Comment by bhikkhu-kosalla-china** [comment]
学员反馈：
这个2.0新版本，相较于之前的版本，就是一片白，有点刺眼，不象老版本的画面层次丰富，字体有粗有细，字的颜色有黑色、咖色，背景色是绿色，护眼效果比较好，字典、文本等等版块也更清晰……

**Comment by visuddhinanda** [comment]
已经修复

https://next.wikipali.org/pcd/article/chapter/64-190?mode=edit&channel=41612a55-a8a6-4724-921f-bf0dcc319f89
