### ISSUE TITLE
🎨 显示问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1350]
这个2.0新版本，相较于之前的版本，就是一片白，有点刺眼，不象老版本的画面层次丰富，字体有粗有细，字的颜色有黑色、咖色，背景色是绿色，护眼效果比较好，字典、文本等等版块也更清晰……
——学员反馈

**Comment by visuddhinanda** [comment]
颜色问题不好解决。护眼的话先凑合用暗黑模式吧。
