### ISSUE TITLE
🐛 巴利原文无法复制

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1352]
![image](https://github.com/iapt-platform/mint/assets/84234053/85f23a3a-5acf-4ffd-b57b-67ad86cf7957)

这里的巴利原文在翻译过程中如果想要复制，会出现下列内容：

阅读
翻译
逐词解析
Paṭṭhānappakaraṇa-aṭṭhakathā/
Paṭṭhānappakaraṇa-aṭṭhakathā
Paccayuddesavaṇṇanā
初译·高级班内部讨论
4
|
0
|
|
3%
更多
1889
Paccayuddesavaṇṇanā
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1889-2-2
1890
Sammāsambuddhena
hi
anulomapaṭṭhāne
dvāvīsati
tike
nissāya
tikapaṭṭhānaṃ
nāma
niddiṭṭhaṃ
,
sataṃ
duke
nissāya
dukapaṭṭhānaṃ
nāma
niddiṭṭhaṃ
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1890-2-18
Tato
paraṃ
dvāvīsati
tike
gahetvā
dukasate
pakkhipitvā
dukatikapaṭṭhānaṃ
nāma
dassitaṃ
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1890-19-29
Tato
paraṃ
dukasataṃ
gahetvā
dvāvīsatiyā
tikesu
pakkhipitvā
tikadukapaṭṭhānaṃ
nāma
dassitaṃ
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1890-30-40
Tike
pana
tikesuyeva
pakkhipitvā
tikatikapaṭṭhānaṃ
nāma
dassitaṃ
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1890-41-48
Duke
ca
dukesuyeva
pakkhipitvā
dukadukapaṭṭhānaṃ
nāma
dassitaṃ
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1890-49-56
Evaṃ
–
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1890-57-58
1891
Tikañca
paṭṭhānavaraṃ
dukuttamaṃ
,
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1891-2-5
1892
Dukaṃ
tikañceva
tikaṃ
dukañca
;
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1892-2-6
1893
Tikaṃ
tikañceva
dukaṃ
dukañca
,
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1893-2-6
1894
Cha
anulomamhi
nayā
sugambhīrāti
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1894-2-6
1895
Paccanīyapaṭṭhānepi
M0.0342dvāvīsati
tike
nissāya
tikapaṭṭhānaṃ
nāma
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1895-2-9
Dukasataṃ
nissāya
dukapaṭṭhānaṃ
nāma
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1895-10-14
Dvāvīsati
tike
dukasate
pakkhipitvā
dukatikapaṭṭhānaṃ
nāma
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98-1895-15-21
Dukasataṃ
dvāvīsatiyā
tikesu
pakkhipitvā
tikadukapaṭṭhānaṃ
nāma
.
请输入
0
译文
Nissaya
注疏
相似句
关系图
Paṭṭhānappakaraṇa-aṭṭhakathā
98

显然，这个复制的结果完全无法使用。这个想要在编辑状态下复制巴利语。

[问题链接](https://next.wikipali.org/pcd/article/chapter/98-1889?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
要复制纯文本还是markdown|html。需要带格式吗？比如黑体。

**Comment by bhikkhu-kosalla-china** [comment]
这个第一步先能复制再说；如果可以带格式是比较好的。

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/a569378b-1d2d-4609-80f2-b83351c96120)

**Comment by visuddhinanda** [comment]
已经修复
