### ISSUE TITLE
🐛 注释书跳转功能尚未恢复

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1354]
![image](https://github.com/iapt-platform/mint/assets/84234053/ec647672-f9a8-4f29-a521-81564d9d3f53)

[问题链接](https://next.wikipali.org/pcd/article/para/undefined?mode=edit&book=67&par=913&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
1.0版也没有。是数据问题

![image](https://github.com/iapt-platform/mint/assets/63999293/cead8809-7d48-454f-bb76-75e6fb9c57e8)
