### ISSUE TITLE
🐛 点词查询被遮挡

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1355]
![image](https://github.com/iapt-platform/mint/assets/84234053/58fa60fc-4c0d-4797-ad6c-f7f9e68bdc6f)

发现有个别词无法点击，通过代码查看器发现被一个未知元素遮挡

[问题链接](https://next.wikipali.org/pcd/article/chapter/98-2049?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/a090e80f-05eb-4c9b-9e4d-bf651758008f)
