### ISSUE TITLE
🐛 添加译文的channel结果显示他人channel

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1356]
https://github.com/iapt-platform/mint/assets/84234053/f92e72ea-cd4d-4cde-af46-18fa77fe278f

添加自己的译文，结果显示他人channel，而且显示多个同样的channel

[问题链接](https://next.wikipali.org/pcd/article/chapter/98-2049?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
录像没看懂。什么操作？这个录屏软件支持录制鼠标箭头吗？一开始就是多个相同的channel

![image](https://github.com/iapt-platform/mint/assets/63999293/fc04d6ed-9345-4008-9248-1439523cea1e)

**Comment by visuddhinanda** [comment]
我这里显示没问题

![image](https://github.com/iapt-platform/mint/assets/63999293/8f7e893c-6ddd-48a0-9f88-b3f58f37d547)

**Comment by visuddhinanda** [comment]
哦，看明白了。

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/38eadf3e-38c1-4504-974a-cd089f6e8edc)
