### ISSUE TITLE
🐛 单段落显示无法复制整段的句子编号

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1379]
![image](https://github.com/iapt-platform/mint/assets/84234053/26ace071-b156-47ba-aab4-1cb81f008123)

单独一段显示的时候没有显示段落号，以至于无法复制整段的句子编号

[问题链接](https://next.wikipali.org/pcd/article/para?mode=edit&channel=40b9f2e6-cfcd-4e18-809b-3375e75ef88b&book=96&par=1791)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/5278ec37-d3d2-4264-9bf0-82e78361ec9a)
