### ISSUE TITLE
🐛 逐词译状态巴利原文无法显示

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1382]
![b9a6cfa98ce3168f89f39e28942b852](https://github.com/iapt-platform/mint/assets/84234053/8af04270-cd57-488a-b9fe-64bf6cb008bc)

某用户的巴利原文显示为汉字注音，且无法修改

[问题链接](https://next.wikipali.org/pcd/article/article/f9f3daf1-bbac-423e-98ce-8ef66da0e686?mode=wbw&channel=26440478-bc80-41bb-9481-9bb61889795b&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d#eka-Concise)

**Comment by visuddhinanda** [comment]
让他把谷歌网页翻页关掉
