### ISSUE TITLE
🐛 nissaya气泡不能实时更新

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1384]
![image](https://github.com/iapt-platform/mint/assets/84234053/1020024d-c648-4057-885c-79b2ef78b5ec)

在新增内容之后，译文中显示的气泡和新窗口中打开的显示结果不同

[问题链接](https://next.wikipali.org/pcd/article/para/67-911?mode=edit&book=67&par=911&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
这个原因是气泡用了缓存。好处是一样的气泡只需要加载一次。下次加载无需等待。但是缓存的生命周期和浏览器的是一样的。也就是说，浏览器关闭，缓存失效。刷新页面也没用。**只能关闭浏览器，再打开**。如果不用缓存，用户体验感不好，老是要加载。laravel api又比较慢。
所以，这个问题不好解决。
