### ISSUE TITLE
🐛 无法在逐词解析模式下优先显示其他版本风格的译文

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1386]
![image](https://github.com/iapt-platform/mint/assets/84234053/32293a0d-c34f-48f3-82b0-a89dd55437e8)

初级班学员的一项作业，就是对照某个指定channel的译文写自己的逐词译。然而，由于逐词译和译文的channel捆绑，无法同时显示自己的逐词译和教材指定的译文。

需求：能够同时展示学员的逐词译和教材指定的译文，且教材指定译文在优先显示的位置上。

[问题链接](https://next.wikipali.org/pcd/article/article/f9f3daf1-bbac-423e-98ce-8ef66da0e686?mode=wbw&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d&channel=26440478-bc80-41bb-9481-9bb61889795b)

**Comment by visuddhinanda** [comment]
>无法同时显示自己的逐词译和教材指定的译文。

选择两个channel 用户的在前面，参考译文在后面。

默认第一个channel有逐词解析是为了简化用户操作。否则，用户还要指定要显示哪个channel的逐词解析，比较麻烦。

**Comment by bhikkhu-kosalla-china** [comment]
[问题链接](https://next.wikipali.org/pcd/article/article/f9f3daf1-bbac-423e-98ce-8ef66da0e686?mode=wbw&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d&channel=26440478-bc80-41bb-9481-9bb61889795b_41612a55-a8a6-4724-921f-bf0dcc319f89)

无法选择两个channel

**Comment by visuddhinanda** [comment]
已经修复

https://next.wikipali.org/pcd/article/article/f9f3daf1-bbac-423e-98ce-8ef66da0e686?mode=wbw&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d&channel=26440478-bc80-41bb-9481-9bb61889795b_41612a55-a8a6-4724-921f-bf0dcc319f89
