### ISSUE TITLE
🐛 回复功能问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1387]
![image](https://github.com/iapt-platform/mint/assets/84234053/02a7890f-3ba5-4f9d-ac28-7cfc5fb5ebbc)

- [ ] 回复按钮隐藏太深

- [ ] 回复的展示是二级展示，不方便
- [ ] 推送的[链接](https://next.wikipali.org/pcd/discussion/topic/fdd4ef18-432e-11ee-a066-b3552db34b9c)只能看到回复，看不到主题

[问题链接](https://next.wikipali.org/pcd/article/chapter/98-2039?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

大家普遍建议参考[百度贴吧](https://tieba.baidu.com/f?kw=%E4%BD%9B%E9%97%A8&fr=index)

![image](https://github.com/iapt-platform/mint/assets/84234053/a10f0520-aac7-4c71-9e43-56d6c135c3b1)

**Comment by bhikkhu-kosalla-china** [comment]
回复的页面在填写时候造成迷惑
![image](https://github.com/iapt-platform/mint/assets/84234053/3af4ea5c-94c3-4afd-8a9e-6c909db87c84)

**Comment by visuddhinanda** [comment]
已经添加 回复按钮

![image](https://github.com/iapt-platform/mint/assets/63999293/76d9b727-21be-4985-b1e2-e74d5692e328)

**Comment by visuddhinanda** [comment]
已经修复
