### ISSUE TITLE
🐛 个别元素过高，遮挡保存按钮，导致无法保存

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1388]
![image](https://github.com/iapt-platform/mint/assets/84234053/3114f859-ac63-41f7-a543-73b6cd346599)
![image](https://github.com/iapt-platform/mint/assets/84234053/9a02c276-b0a4-46a2-b02d-9c5f706b4af3)

[问题链接](https://next.wikipali.org/pcd/article/chapter/98-2039?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
已经修复
