### ISSUE TITLE
🎨 无数据社区词典没有隐藏

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1389]
![image](https://github.com/iapt-platform/mint/assets/84234053/4138deb6-1261-47a9-ab6d-8282ccb4f80c)

没有数据的社区词典不隐藏，则带来很多冗余显示

[问题链接](https://next.wikipali.org/pcd/dict/upatthambhaka)

**Comment by visuddhinanda** [comment]
已经修复
![image](https://github.com/iapt-platform/mint/assets/63999293/1a45e34d-cb54-4e61-8d71-4ab4382e8d31)
