### ISSUE TITLE
🐛 顶端工具栏缺失搜索等功能

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1390]
![image](https://github.com/iapt-platform/mint/assets/84234053/0b51bb27-90d0-4d43-8e4a-d26327e527ef)

![image](https://github.com/iapt-platform/mint/assets/84234053/2111d124-53e6-49ba-a137-7981b895a994)
需要在这里增加`译经楼` `语言切换` `搜索🔍︎`

**Comment by bhikkhu-kosalla-china** [comment]
搜索图表是急需的，因为现在大家都找不到搜索入口

**Comment by visuddhinanda** [comment]
**搜索图表**是什么？

**Comment by visuddhinanda** [comment]
'语言切换' 在翻译时不常用

其余的已经添加

![image](https://github.com/iapt-platform/mint/assets/63999293/efc054bc-2a46-48e4-a117-5c6c434cce0c)
