### ISSUE TITLE
🐛 刚刚维护的术语存在bug

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1398]
![image](https://github.com/iapt-platform/mint/assets/84234053/1cc8151f-bdb4-475e-9e15-8d0a29ce21f1)
上文维护了术语，但是在术语下拉列表中没有
![image](https://github.com/iapt-platform/mint/assets/84234053/50b5de14-f536-4b37-ad34-5f48095b735d)
修改译文后，之前维护的术语丢失。

术语拼写：hirikopīna
[问题链接](https://next.wikipali.org/pcd/article/article/09b50293-260d-4b63-aeb6-5509903fcc3e?mode=edit&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d&channel=41612a55-a8a6-4724-921f-bf0dcc319f89)
句子编号
- 64-191-196-202

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/81b7115b-d20d-4177-baf0-5244a2b971c4)
