### ISSUE TITLE
🐛 相似句的注释、译文、nissaya无法展开

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1399]
![image](https://github.com/iapt-platform/mint/assets/84234053/1fb62fdc-f35e-40c1-98d3-3d97329a4076)

相似句的注释、译文、nissaya无法展开

[问题链接](https://next.wikipali.org/pcd/article/chapter/98-1937?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/84234053/9d632c3b-e8a2-48cc-9e0c-e32b95b750b6)
相似句的nissaya展开后没反应
![image](https://github.com/iapt-platform/mint/assets/84234053/8acd47be-79f2-483a-ac52-e954b1d46c2e)
查看原句发现确实有nissaya

[问题链接](https://next.wikipali.org/pcd/article/para/65-936?mode=edit&book=65&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43&par=936)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/81a3fd02-b84c-4d10-8faf-fc0159cc6ccc)
