### ISSUE TITLE
相似句比较

### ISSUE THREAD

**Issue by Bhikkhu-Kosalla** [iapt-platform/mint#14]
# 需求描述
1. 给出一个句子，能够在句子库中找到词语组成相似的句子。这可以提高翻译的效率，并能够帮助百科词条的制作。
2. 保证性能控制在2s之内能够给出前20个结果
3. 不给出任何句子，能够找到相似度在某个范围内相似的句子并建立数组，找到元素最多的句子数组。
# 句子库文件（含数据库及拆分句子的php）
- 句子数据库拆分结果 sqlite格式 
    - dropbox [链接](https://www.dropbox.com/s/t452yiwkv205qzs/pali_sent.7z?dl=0)
    - 百度网盘 [链接](https://pan.baidu.com/s/12IrhMkeo4g-z5wP_LeUeOA)  提取码：pali
- 语料库逐句拆分代码：https://github.com/iapt-platform/mint/blob/master/app/install/db_insert_sentence.php
- 语料库数据目录：待 @visuddhinanda 上传
# 比较方法 
1.设X是所有文本。对于X中的每个word w，计算其出现的次数count(w)。有些可能出现很多词，大多数可能出现1次。定义词频 freq(w)=1/count(w)。freq越大，说明这个词越稀罕，就越有信号。
复合词可以在这里处理。w可以规定为基本词。
2.给出两句sentence s1，s2 如何计算他们的相似度 similarity(s1, s2)呢？
- (a)计算s1的“词长度” = sqrt(sum((count(w)*freq(w))^2)) w为s1的所有单词，count(w)是w在s1出现的次数，freq(w)是之前第一步计算的词频。
- (b)同理 计算s2的“词长度”
- (c)计算s1和s2的“共同词长度” = sum(count_s1(w)*freq(w)*count_s2(w)*freq(w)) w为共同出现在s1和s2的单词。count_s1(w)是w在s1出现的次数，count_s2(w)是w在s2出现的次数。
- (d)计算similarity=(c)/((a)*(b))
这就是cosine distance算法。而里面用到的值叫tfidf。
注意：
- 1.freq(w)可以存在数据库里，然后调到内存里 
- 2.计算后数值可能很小，用64-bit double
实验：找出若干句典型的句子，通过以上算法看看是否能找到相似句。譬如 找s的相似句，把X中所有句子都和s匹配一下，然后把similarity值排序。最大的值最相似。排名第一应该是s，可以证明similarity(s, s)肯定是1.0 如果不是，程序有bug。
先做到这一步。如果效果好，那么大部分的难题已经解决。接下去只要把算法速度优化，避免O（n^2）。如果实验效果不好，我们再寻找其他算法。
优化是用locality sensitive hashing LSH算法，但如果效果不好，我们要先调效果 再考虑效率。
这样才能保证 similarity(s, s) = 1.0
[余弦相似性](https://en.wikipedia.org/wiki/Cosine_similarity)

**Comment by visuddhinanda** [comment]
句子数据库 sqlite格式  https://www.dropbox.com/s/t452yiwkv205qzs/pali_sent.7z?dl=0
