### ISSUE TITLE
🐛 空注释依然显示数字

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1400]
![image](https://github.com/iapt-platform/mint/assets/84234053/d4d04be6-4ca3-49c8-b6a7-ff459bd5bd8e)

在1.0里面，如果数据是有记录的空数据，那么在统计的时候依然不显示数字。

[问题链接](https://next.wikipali.org/pcd/article/article/09b50293-260d-4b63-aeb6-5509903fcc3e?mode=edit&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d&channel=41612a55-a8a6-4724-921f-bf0dcc319f89)

问题句子编号：192-541-102-117

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/c7bfbf4d-897e-42af-8630-2932e080441b)
