### ISSUE TITLE
🐛 链接不能在新页面中打开

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1404]
![image](https://github.com/iapt-platform/mint/assets/84234053/805d0d30-3ce4-49c3-b5aa-939bc9e7f774)

这里的编辑按钮无法，即便按住`ctrl`也无法在新页面中打开。

[问题链接](https://next.wikipali.org/pcd/article/article/a78bf897-399c-4032-b8ca-66cab58e070f?mode=read&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d)

**Comment by visuddhinanda** [comment]
已经修复
