### ISSUE TITLE
🐛 术语功能的使用问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1405]
![image](https://github.com/iapt-platform/mint/assets/84234053/d7edec04-8b59-478b-98ec-0efbbfa27008)

由于默认设置为move往往被用户忽略，而提交的时候显示错误提示，且不知道怎么回事。

![33bf012bf24b02d78fb0295c18ae9a08](https://github.com/iapt-platform/mint/assets/84234053/55a6f0d8-194e-422f-a514-6f5e83ad7509)

改进建议：
- 默认选项为copy
- 错误提示说明是不能删除还是不能写入
    - if(写入版本无权限) then 您无权修改当前术语，请选择你自己有权限的版本风格，或联系拥有者分配权限
    - else if(被移动的版本无权限) then 您无权移动原有的术语，请将move改为copy，或联系拥有者分配权限

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/a4d3848d-7fca-4371-bf9c-d1c625582f2e)
