### ISSUE TITLE
🐛 搜索结果的链接不方便

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1406]
![image](https://github.com/iapt-platform/mint/assets/84234053/695afecd-8c5d-405f-b94b-d338a67d9470)

滚动到底之后，既不能加载后续段落，也不能用翻页按钮翻页

[搜索页面链接](https://next.wikipali.org/pcd/search/key/ci%C3%B1cam%C4%81%E1%B9%87avik%C4%81)
[结果链接](https://next.wikipali.org/pcd/article/para?mode=edit&channel=7ac4d13b-a43d-4409-91b5-5f2a82b916b3&book=122&par=2698)

**Comment by visuddhinanda** [comment]
已经修正
