### ISSUE TITLE
🐛 术语修改后不更新

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1408]
![lQLPJw55IR_XAGzNA23NA1ywd09awHl7ILwE40lfdwAoAA_860_877](https://github.com/iapt-platform/mint/assets/84234053/720ae825-5ac3-478d-a10e-9eda84f69dd6)

修改5天，仍然没有更新术语

![lQLPJw55IR_XAGzNA23NA1ywd09awHl7ILwE40lfdwAoAA_860_877](https://github.com/iapt-platform/mint/assets/84234053/676b1d56-1e46-41c3-84c3-ba476bae9ffd)
![lQLPJx7Qzg9PSyzNAQTNBX-w5bfoh_n3ChME40m2nIDVAA_1407_260](https://github.com/iapt-platform/mint/assets/84234053/5653fbff-7dcd-41d6-8c84-d3c77bc7d516)
确定是同一个channel
![debc81d388a69d703b4afa476029f025](https://github.com/iapt-platform/mint/assets/84234053/fb7caab7-9a73-45e9-bc65-634a6169f60a)

[术语链接](https://next.wikipali.org/pcd/term/list/kammasamu%E1%B9%AD%E1%B9%ADh%C4%81na)

不展示新术语的[翻译页面链接](https://next.wikipali.org/pcd/article/chapter/98-2039?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
已经修复
