### ISSUE TITLE
🐛 侧边栏显示问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1413]
![image](https://github.com/iapt-platform/mint/assets/84234053/8ee604fe-00c7-4172-9785-c75d607a9d0d)

如果在点开目录侧边栏之后，如果不收回，点开词典，则两者显示有重叠

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/d5a03218-0ea5-456e-b651-62b0d9881391)
