### ISSUE TITLE
🐛 视频显示尺寸过大

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1414]
![image](https://github.com/iapt-platform/mint/assets/84234053/01d01123-e014-4359-b248-d673231ce05d)

显示尺寸过大无法观看，且article中的设置无效

![image](https://github.com/iapt-platform/mint/assets/84234053/2cd3ec10-b216-453f-8e2c-bb1bc00bcd5c)

[问题链接](https://next.wikipali.org/pcd/article/article/f0735b5e-5c90-493e-a47d-f495c6d329fa?channel=41612a55-a8a6-4724-921f-bf0dcc319f89)

**Comment by bhikkhu-kosalla-china** [comment]
此bug与初级班相关

**Comment by visuddhinanda** [comment]
不建议初级班用2.0 。 bug太多了

已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/a63a9a10-496c-4152-904f-4e0d4e2e6659)
