### ISSUE TITLE
🐛 修改建议pr无原文显示

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1415]
![image](https://github.com/iapt-platform/mint/assets/84234053/d54090b2-412f-49d0-919f-e3ed8e773d53)

和之前`讨论`遇到的问题是一样的

[链接](https://next.wikipali.org/pcd/article/chapter/166-420?mode=edit&channel=06c4682f-f79a-43fa-a6a9-cad716cc3f5a)

另外，是否可以考虑取消蒙板，这样也是一种

**Comment by visuddhinanda** [comment]
已经修改
