### ISSUE TITLE
🐛 版本迁移时，原作者信息丢失

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1416]
![image](https://github.com/iapt-platform/mint/assets/84234053/d3b5b8d5-1ea0-4f65-b43e-e40442e861d3)
原作者是sumedhā小善慧，然而这里显示的时间是原作者的贡献时间，但名字是迁移者的名字
![image](https://github.com/iapt-platform/mint/assets/84234053/67c66d2b-bac0-482b-b99b-91bd723aba0b)
在历史记录中也没有原作者的信息

[问题链接](https://next.wikipali.org/pcd/article/para/194-321?mode=edit&book=194&par=321&channel=74ebf4c5-c243-4948-955d-6c277e29276a)

**Comment by bhikkhu-kosalla-china** [comment]
事关网站信誉和著作权，因此标注紧急

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/d2dbcfa2-afcd-404d-a71e-ee2ec1b812be)
