### ISSUE TITLE
🆙 术语下拉菜单排序逻辑问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1417]
![image](https://github.com/iapt-platform/mint/assets/84234053/ea6b4e67-c0b9-4136-9cb6-8c8e76f38fa5)

这里，术语下拉菜单的匹配逻辑中，paccaya排名没有靠前
但paccaya确实有术语，[链接](https://next.wikipali.org/pcd/term/list/paccaya)
因此，当前的术语排序的匹配逻辑存在问题。

[问题链接](https://next.wikipali.org/pcd/article/chapter/166-420?mode=edit&channel=06c4682f-f79a-43fa-a6a9-cad716cc3f5a_ca69f92f-17ef-4664-9559-47fffd5869f2)

**Comment by bhikkhu-kosalla-china** [comment]
应该依照输入内容与拼写的相似度进行排序

**Comment by visuddhinanda** [comment]
按照拼写的长度排序

![image](https://github.com/iapt-platform/mint/assets/63999293/7bdf8c12-e809-4cac-9eb2-451820b81c7e)
