### ISSUE TITLE
🐛 术语不及时更新问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1426]
![image](https://github.com/iapt-platform/mint/assets/84234053/d4364eaf-2470-4cd1-8a69-5dca50edde01)
![image](https://github.com/iapt-platform/mint/assets/84234053/a0350226-82f6-489e-8f07-2f37345abb99)

术语不能及时更新，导致很急用的翻译内容在分享给他人的时候出现问题。

[链接](https://next.wikipali.org/pcd/article/para/132-376?mode=edit&book=132&par=376&channel=74ebf4c5-c243-4948-955d-6c277e29276a)

注：因为已经过去一段时间，可能看不出来了。

**Comment by visuddhinanda** [comment]
与 #1408 重复
