### ISSUE TITLE
🐛 经典目录缺失

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1434]
![image](https://github.com/iapt-platform/mint/assets/84234053/b7a904b8-1a77-47fe-8cb0-c20e9c5fa866)

发趣论一丢失
1.0中未丢失
![image](https://github.com/iapt-platform/mint/assets/84234053/56c75baf-9b0b-4e53-b6d9-2d79cbb127d4)

[问题链接](https://next.wikipali.org/pcd/palicanon/list/default/abhidhammapi%E1%B9%ADaka_pa%E1%B9%AD%E1%B9%ADh%C4%81na)

**Comment by bhikkhu-kosalla-china** [comment]
进入读经界面后的目录也有问题
![image](https://github.com/iapt-platform/mint/assets/84234053/1db371b2-dc4f-4fcd-b16d-b7baf6fdb3db)

[问题链接](https://next.wikipali.org/pcd/article/chapter/81-1388?mode=edit&channel=06415a88-f674-4f00-9bbc-110eddcd365a)

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/b4488420-1460-4c56-977a-0b196d013bd0)
这个目录层级是不是正确的？是否需要把这个tikapathana改成level=1?
2.0外面只显示了level=1

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/6455157f-886a-4c99-a0f1-20a2538c0670)

![image](https://github.com/iapt-platform/mint/assets/63999293/348c408d-67a1-4aae-8a28-ccb6dc49236b)
