### ISSUE TITLE
🐛 问答页面的使用困难

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1435]
![image](https://github.com/iapt-platform/mint/assets/84234053/f8e3e10d-000e-40ba-88f0-6eadf4334faa)

在回答问题的时候，需要用到词典功能，也需要看到上下文（上下三段）。

[问题链接](https://next.wikipali.org/pcd/discussion/topic/ecfc1b0e-4c74-11ee-a067-b7127fdab099)

**Comment by visuddhinanda** [comment]
已经修复
