### ISSUE TITLE
🆙 分享功能中对组群名、用户名搜索的匹配逻辑

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1438]
![image](https://github.com/iapt-platform/mint/assets/84234053/d4399dd0-8d1c-4bb3-b63c-31db46ba88ec)
![image](https://github.com/iapt-platform/mint/assets/84234053/2acdf4ca-8ddc-4984-9920-2eceafb597e9)

目前只能最精确的匹配，即便“协作”出现在后面都无法匹配到。
而且iapt和IAPT的大小写目前也是精准匹配
![image](https://github.com/iapt-platform/mint/assets/84234053/431615e0-b4bf-4748-bf24-6ee22c052b65)

在实际使用中，但实际情况是往往记不住全名，只能记住关键词，比如`iapt`，`协作`。如果无法模糊匹配，使用起来就存在困难。

[问题链接](https://next.wikipali.org/pcd/studio/iapt/channel/list)

**Comment by visuddhinanda** [comment]
已经修复。
![image](https://github.com/iapt-platform/mint/assets/63999293/74ebdaa1-e65a-4d29-b0a5-405f7723509e)

大小写改起来很麻烦，以后再说吧
