### ISSUE TITLE
🐛 讨论回复的显示问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1445]
![image](https://github.com/iapt-platform/mint/assets/84234053/ef7a9718-905c-45d8-86c3-0bd0c77636d5)
这是刚刚提交回复之后
![image](https://github.com/iapt-platform/mint/assets/84234053/d03a775a-3e8d-473e-a671-11b7645948b2)
这是刷新之后
回复的排序应该依照时间升序，这样符合论坛的显示模式

另外，删除后显示出现bug
![image](https://github.com/iapt-platform/mint/assets/84234053/c919e843-2d09-4caa-9ca5-e49611d37d20)
删除前
![image](https://github.com/iapt-platform/mint/assets/84234053/a84e0a69-2d6f-4227-b4dd-f552b5459b69)
删除后

刷新后恢复正常，说明数据交互上没有bug，但前台显示有bug。

[问题链接](https://next.wikipali.org/pcd/discussion/topic/b7262996-4c99-11ee-a067-87536f50fada#99e9b7b2-4d84-11ee-a069-9fa987aed1e4)

**Comment by visuddhinanda** [comment]
已经修复
