### ISSUE TITLE
🐛 注疏中有内容，但不显示数字

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1447]
![image](https://github.com/iapt-platform/mint/assets/84234053/2bf001cb-6852-40a1-8438-50538510a07f)

刚刚穿插的注释，外表看不出来有注释，点击可以展开，且有内容

[问题链接](https://next.wikipali.org/pcd/article/para?mode=edit&channel=3b0cb0aa-ea88-4ce5-b67d-00a3e76220cc&book=65&par=450)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/1e930107-8585-4d63-9c26-9eaaccfa9510)
