### ISSUE TITLE
🐛 discuss 显示bug

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1456]
![image](https://github.com/iapt-platform/mint/assets/84234053/5fe74d4f-9563-4fdb-aa1c-6ebcc14a48e0)
标题显示不全， 导致问题看不全
只有点击回复才能看全
![image](https://github.com/iapt-platform/mint/assets/84234053/81435de9-c957-4889-9e02-8f9c02b92d77)

且在回复状态下，点击新的问题，不会自动跳转
![image](https://github.com/iapt-platform/mint/assets/84234053/bf61dfeb-7e61-4bc6-8eae-19d6395bd9f9)

[问题链接](https://next.wikipali.org/pcd/article/article/09b50293-260d-4b63-aeb6-5509903fcc3e?mode=edit&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d&channel=41612a55-a8a6-4724-921f-bf0dcc319f89)

**Comment by visuddhinanda** [comment]
bug在哪里？

**Comment by visuddhinanda** [comment]
已经修复
