### ISSUE TITLE
🐛 术语修改保存后，社区术语依然是绿色

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1457]
![image](https://github.com/iapt-platform/mint/assets/84234053/1d35b197-1172-4c4d-bb38-9eea782554b5)

术语修改成自己的之后，颜色依然是绿色；用户会怀疑“我修改的内容有没有进到我的channel里面？”
刷新之后变蓝色，

![image](https://github.com/iapt-platform/mint/assets/84234053/f0b0ca20-ab3b-43e8-92ed-45aef50ee8ae)

[问题链接](https://next.wikipali.org/pcd/article/para/66-161?mode=edit&book=66&par=161&channel=41612a55-a8a6-4724-921f-bf0dcc319f89)

**Comment by visuddhinanda** [comment]
已经修复
