### ISSUE TITLE
🐛 翻页后滚动条位置不归零

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1483]
![image](https://github.com/iapt-platform/mint/assets/84234053/517aa14a-0ccf-4891-ad71-2a04ed974583)

当[页面](https://next.wikipali.org/pcd/article/para/98-2029?mode=edit&book=98&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43&par=1890)展开注疏后滚动到底部时，点击下一页
跳转之后滚动条位置应该归零，但依然保持原有状态

![image](https://github.com/iapt-platform/mint/assets/84234053/82394793-0b7e-4a5f-8fd7-6faa5d160e34)

**Comment by visuddhinanda** [comment]
已经修复
