### ISSUE TITLE
🆙 讨论的译文历史修改

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1487]
![image](https://github.com/iapt-platform/mint/assets/84234053/10620d3b-af6a-463f-9ba7-b275ce501e50)
需求一：在展示译文修改脉络时，希望回复与回复之间的修改历史记录只展示最接近下一条回复的一次。
因为在实际修改的时候，经常连续改动三次保存三次；如果都展示学员表示会很有压力，会让展示的结果变冗长，有负罪感

需求二：修改痕迹的展示，依照展示的内容进行文本比对计算，而不是依照时间轴

需求三：topic和第一条回复之间，需要展示topic建立时的最新译文

[链接](https://next.wikipali.org/pcd/article/article/28279c02-f119-48ba-a1fd-0ee1f41964c0?mode=edit&channel=41612a55-a8a6-4724-921f-bf0dcc319f89&anthology=cd235b46-d35f-42a9-9653-733cdb9a1e8d)

**Comment by visuddhinanda** [comment]
![image](https://github.com/iapt-platform/mint/assets/63999293/fd5d4791-41d4-44d4-b116-97769850e1d6)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/b0c7e374-e33a-4c37-b17e-5e9d230e30b3)

![image](https://github.com/iapt-platform/mint/assets/63999293/4c98118f-4423-45c1-b2a4-72b22e8e1b29)

**Comment by bhikkhu-kosalla-china** [comment]
如果变成
#某用户#在6天前根据#某channel#6天前的译文创建话题
这样会不会好看一些？
