### ISSUE TITLE
🐛依照模版连续提交回复，会建立两个话题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1517]
![image](https://github.com/iapt-platform/mint/assets/84234053/025772ba-8a0b-4ad2-9623-b0d2ae50e5e4)

用模版提交回复之后，再次提交回复，建立了两个话题，且默认链接没有更新

![image](https://github.com/iapt-platform/mint/assets/84234053/5ffce239-9eb1-40ca-8fb0-82be6426b681)

**Comment by visuddhinanda** [comment]
>默认链接没有更新
是什么意思？

**Comment by visuddhinanda** [comment]
已经修复

**Comment by bhikkhu-kosalla-china** [comment]
> 已经修复

![image](https://github.com/iapt-platform/mint/assets/84234053/6abfb568-27c3-48b6-9621-8b5339957b9e)

链接复制出来是这样：https://next.wikipali.org/pcd/discussion/topic/undefined

必须退出再刷新，链接才恢复正常
