### ISSUE TITLE
🐛 话题模版展开后，导致巴利原文消失

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1518]
https://github.com/iapt-platform/mint/assets/84234053/f4c83987-a544-4032-9813-1a66fc7364c2

[链接](https://next.wikipali.org/pcd/article/chapter/98-2035?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43)

**Comment by visuddhinanda** [comment]
已经修复
