### ISSUE TITLE
默认模板链接获取错误

### ISSUE THREAD

**Issue by visuddhinanda** [iapt-platform/mint#1527]
![image](https://github.com/iapt-platform/mint/assets/84234053/6abfb568-27c3-48b6-9621-8b5339957b9e)

链接复制出来是这样：https://next.wikipali.org/pcd/discussion/topic/undefined

必须退出再刷新，链接才恢复正常

_最初由 bhikkhu-kosalla-china 在 https://github.com/iapt-platform/mint/issues/1517#issuecomment-1728847648 发布_

**Comment by bhikkhu-kosalla-china** [comment]
测试成功
