### ISSUE TITLE
🆙 需要在1.0中添加2.0入口

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1558]
现在很需要

**Comment by visuddhinanda** [comment]
已经添加按钮

测试链接  https://next.wikipali.org/app/article/index.php?view=chapter&book=64&par=167&channel=7ac4d13b-a43d-4409-91b5-5f2a82b916b3

![image](https://github.com/iapt-platform/mint/assets/63999293/9473b98c-0ec7-4833-aaf5-5a2ae24d40c2)

**Comment by bhikkhu-kosalla-china** [comment]
在www-hk开头的域名中没有变，在next中有改变；是否考虑：
- www-hk的代码修改
- www-hk进入的任何链接都自动跳转next

**Comment by visuddhinanda** [comment]
www-hk加到新版的跳转。需要等到2. 0每项功能都能用。现在逐词解析自动查词有问题。正在改。

www-hk自动跳转，需要等2. 0稳定之后。就是比上面这个更稳定之后。

**Comment by visuddhinanda** [comment]
已经修复
