### ISSUE TITLE
🐛 文集功能出现不知该如何形容的bug

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1563]
https://github.com/iapt-platform/mint/assets/84234053/546dac3b-426d-4b4f-a4b1-e2ef47dbb6b7

[问题链接](https://next.wikipali.org/pcd/studio/Kosalla_China/anthology/0911697e-b8b2-43cf-afe3-f34a65e22bf0/edit)

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/9a400375-a782-4df9-8669-54e8d1ce3c51)

原因是有重复的文章。为什么重复还不清楚。凡是有link图标的都是跟上面文章有重复的。
