### ISSUE TITLE
📈 markdown导出功能

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1618]
法句项目组的sunanda尊者和法护尊者提出需要导出功能，经过讨价还价，初步需求如下：
格式：markdown
内容：巴利、译文，复选
排版需求：句子和段落能分开即可
其他样式：不要求

**Comment by visuddhinanda** [comment]
已经在做了。PDF , Word

这是样张

![image](https://github.com/iapt-platform/mint/assets/63999293/c6019594-1cd3-4a01-b4e5-53faa82664b1)


![image](https://github.com/iapt-platform/mint/assets/63999293/66ec916a-5c2b-4b0d-be51-c1a99e4dc317)

![image](https://github.com/iapt-platform/mint/assets/63999293/70bb25c6-b6cb-4461-9465-ebeeb5340138)
