### ISSUE TITLE
去掉网页里面全部的不翻墙不能访问的链接

### ISSUE THREAD

**Issue by visuddhinanda** [iapt-platform/mint#1624]

**Comment by visuddhinanda** [comment]
Youtube链接去掉了



![Image](https://github.com/iapt-platform/mint/assets/63999293/382786e7-017e-44f4-8af9-7fa5637e9968)

**Comment by visuddhinanda** [comment]
测试链接 https://staging.wikipali.org/app/studio/index.php

**Comment by bhikkhu-kosalla-china** [comment]
数据库中的内容呢？能否去掉呢？
比如文章、译文里面的内容

**Comment by bhikkhu-kosalla-china** [comment]
还是说我们用代码把相关内容变得不可见？

**Comment by visuddhinanda** [comment]
用户

> 数据库中的内容呢？能否去掉呢？ 比如文章、译文里面的内容

用户数据需要改吗？比如，是否百度贴吧有个帖子里面有个油管链接。版主需要屏蔽这个帖子。如果是的话。可以在客户端做一个过滤。 *.youtube.com* 改成 ####就行了
