### ISSUE TITLE
翻译和逐词解析模式需要有登录验证

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1636]
## 需求
- 防止未登录状态时编辑导致权限出错
- 未登录状态也能看到一些数据：
   - nissaya
   - 注释
   - 相似句

## 方案
触发情况
- 通过网址打开翻译模式或逐词译模式
- 页面内跳转
- 其他需要登录的情况

效果
- 弹出无需用登录页面即可登录的登录弹窗
- 弹窗可关闭

**Comment by visuddhinanda** [comment]
![Image](https://github.com/iapt-platform/mint/assets/63999293/b9f8750b-d5ce-49b1-91bd-6bd43246e97b)

**Comment by bhikkhu-kosalla-china** [comment]
> @bhikkhu-kosalla-china 这个效果行吗？
> 
> ![Image](https://user-images.githubusercontent.com/63999293/279037281-b9f8750b-d5ce-49b1-91bd-6bd43246e97b.png)

能用蒙板吗？蒙板比较烦人，提醒效果比较强

另外，措辞改为：
`您尚未登录，只能查看公开数据，其他功能无法使用`

**Comment by visuddhinanda** [comment]
>能用蒙板吗？蒙板比较烦人，提醒效果比较强

怕用户讨厌。没有账户的人是允许用翻译模式的。

**Comment by visuddhinanda** [comment]
![Image](https://github.com/iapt-platform/mint/assets/63999293/33ebc81b-5c73-4490-a33b-9bc80e04ac7c)

**Comment by visuddhinanda** [comment]
![Image](https://github.com/iapt-platform/mint/assets/63999293/e15d1367-0ab8-4269-9c14-79faccf3cc39)

**Comment by bhikkhu-kosalla-china** [comment]
允许翻译模式没问题，只要提醒一次就OK，我觉着这个挺好
