### ISSUE TITLE
🐛 注疏显示编号不及时

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1647]
![image](https://github.com/iapt-platform/mint/assets/84234053/6199c29b-4c03-4388-a1f3-0e6dfecb393e)

这个不显示编号，导致如果穿插注疏的工作做到一半的时候，如果刷新了页面，就不知道哪些应该展开，哪些不应该展开。
这会导致复注、再复注等三级、四级的工作无法继续
这个无法等待缓存更新，因为这意味着停工等带缓存更新。

[问题链接](https://www.wikipali.cc/pcd/article/chapter/215-474?mode=edit&channel=a19eaf75-c63f-4b84-8125-1bce18311e23_74ebf4c5-c243-4948-955d-6c277e29276a)

**Comment by bhikkhu-kosalla-china** [comment]
修改之后当下改变，但刷新之后仍然是消失的
![image](https://github.com/iapt-platform/mint/assets/84234053/b7ddb0dc-91e0-4c90-b986-569d0f9054f4)

[问题链接](https://staging.wikipali.org/pcd/article/chapter/215-492?mode=edit&channel=a19eaf75-c63f-4b84-8125-1bce18311e23_74ebf4c5-c243-4948-955d-6c277e29276a)句子编号{{215-494-2-18}}

**Comment by visuddhinanda** [comment]
我这里测试没问题 。 句子编号{{215-495-2-21}}。链接同上

https://github.com/iapt-platform/mint/assets/63999293/fa0cbe30-39c3-4a5c-a027-0d095f4a12dc

**Comment by bhikkhu-kosalla-china** [comment]
二次测试，问题消失
