### ISSUE TITLE
🐛 显示出现乱码

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1650]
![image](https://github.com/iapt-platform/mint/assets/84234053/bcf3e123-0641-4d6d-bb3b-5da8c7036b92)

[问题链接](https://www.wikipali.cc/pcd/article/para/215-505?mode=read&book=215&par=505&channel=00b577c1-13b9-11ee-a05a-c3a38e3e3e4d_a19eaf75-c63f-4b84-8125-1bce18311e23)

**Comment by visuddhinanda** [comment]
这个链接是怎么点出来的？

**Comment by bhikkhu-kosalla-china** [comment]
> 这个链接是怎么点出来的？

在[这里](https://www.wikipali.cc/pcd/article/chapter/215-492?mode=edit&channel=a19eaf75-c63f-4b84-8125-1bce18311e23_74ebf4c5-c243-4948-955d-6c277e29276a)点击505段的`仅显示此段`

**Comment by visuddhinanda** [comment]
这里面有两个channel 
00b577c1-13b9-11ee-a05a-c3a38e3e3e4d_a19eaf75-c63f-4b84-8125-1bce18311e23

**Comment by bhikkhu-kosalla-china** [comment]
测试后没问题
