### ISSUE TITLE
🐛 个别词查询导致黑屏

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1676]
问题词：sacca
[链接](https://www.wikipali.cc/pcd/dict/sacca)

没问题的词：paccayesu

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/1f81c945-8da2-4bc1-8ae9-81616ffcebcc)

**Comment by bhikkhu-kosalla-china** [comment]
> 已经修复
> 
测试地址？
