### ISSUE TITLE
🐛 article中句子链接的预览功能没有恢复

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1761]
1.0的article引用句子链接有预览功能
![Image](https://github.com/iapt-platform/mint/assets/84234053/6a620094-c6de-47db-adb7-3fc94acec7f8)
2.0中尚未恢复
![Image](https://github.com/iapt-platform/mint/assets/84234053/c01bec0c-9cd8-4d55-9caf-29b6247899fb)

于是，导致用户被误导，把article写成这样
![Image](https://github.com/iapt-platform/mint/assets/84234053/823fd5e2-107f-4c96-b71e-e7e25336a692)

![Image](https://github.com/iapt-platform/mint/assets/84234053/657dea74-3fdc-4b9c-b997-f0cae5926a3b)

**Comment by visuddhinanda** [comment]
点预览按钮

![image](https://github.com/iapt-platform/mint/assets/63999293/0689672b-9bea-40b4-ac36-47039bad846e)

**Comment by visuddhinanda** [comment]
预览控件不支持自定义模版。

**Comment by visuddhinanda** [comment]
1.0也是要点一下预览按钮的。
