### ISSUE TITLE
[api需求]发送book id列表批量返回Chapter数据信息

### ISSUE THREAD

**Issue by ariyamaggika** [iapt-platform/mint#1762]
传入book id的int数组或者以逗号隔开的string
返回Chapter数据信息列表，包含数据：
![图片](https://github.com/iapt-platform/mint/assets/117618324/a294cec6-088c-4c1d-9ac7-6f76fc35d9d5)

**Comment by visuddhinanda** [comment]
可以用 #1763 里面的api
