### ISSUE TITLE
🐛 无法复制channel中的译文

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1782]
![Image](https://github.com/iapt-platform/mint/assets/84234053/63ddc2a5-4e87-45fd-9d03-ff52504c2619)

[问题链接](https://www.wikipali.org/pcd/article/article/bf6fd379-7049-4dd4-9c0c-af03641ac604?mode=edit&channel=61139a7f-91bf-4446-ac1e-94abbd07db46)

![Image](https://github.com/iapt-platform/mint/assets/84234053/bde6ff3f-c750-441f-abfc-2efed5b2318b)

**Comment by visuddhinanda** [comment]
已经修复
