### ISSUE TITLE
🐛段落模式下无法翻页

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1799]
通过句子的段落跳转到单段显示
![Image](https://github.com/iapt-platform/mint/assets/84234053/89f63e72-ad0a-4115-bda5-6c4874b99a58)
https://www.wikipali.cc/pcd/article/para/151-26?mode=edit&book=151&par=26&channel=9659aefd-11df-42c5-9ae8-08813b2f2b44
然后点击翻页
![Image](https://github.com/iapt-platform/mint/assets/84234053/ba9b0705-527f-4ba6-a4f3-7c40e563f4d0)
https://www.wikipali.cc/pcd/article/para/151-25?mode=edit&book=151&par=26&channel=9659aefd-11df-42c5-9ae8-08813b2f2b44

对比链接发现，这个翻页逻辑只适用于chapter，无法使用与para，151-26变成了151-25，但后面的par=26没有变化，导致翻页失败。

**Comment by visuddhinanda** [comment]
已经修复
