### ISSUE TITLE
🐛搜索结果无法翻页

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1803]
[问题链接](https://www.wikipali.cc/pcd/search/key/katam%C4%81%20%C3%B1%C4%81tapari%C3%B1%C3%B1%C4%81)

![Image](https://github.com/iapt-platform/mint/assets/84234053/953e1b28-86df-4a73-ac27-8244585f8dc9)
![Image](https://github.com/iapt-platform/mint/assets/84234053/1a820003-0318-468c-ae76-cc268e1c8cdc)
第一页和第二页没差别

**Comment by visuddhinanda** [comment]
已经修复
