### ISSUE TITLE
🐛 不登录无法阅读注疏

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1807]
![Image](https://github.com/iapt-platform/mint/assets/84234053/0dab5c5c-b07a-4770-903e-b118adeea8d8)
[链接](https://next.wikipali.org/pcd/article/para/180-1900?book=180&par=1899,1900,1901&focus=1900)

在非登陆状态的阅读模式，无法切换到翻译模式，因为必须要选择channel。
而注疏的查看和阅读又与翻译模式捆绑。
建议在这个页面上增加一个取消按钮——允许非登录用户不选择任何channel

**Comment by bhikkhu-kosalla-china** [comment]
在选择了channel的情况下，只会询问是否以访客身份，并且可以选择不登录
但在未选择channel的情况下，就出现了逻辑bug

**Comment by visuddhinanda** [comment]
已经修改，可以在 next.wikipali.org上测试
