### ISSUE TITLE
🐛 路径链接不能用ctrl跳转

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1819]
![Image](https://github.com/iapt-platform/mint/assets/84234053/0622f37d-822b-491d-b890-f28e493ddb9c)
[问题链接](https://next.wikipali.org/pcd/article/para/64-2103?mode=edit&channel=e5bc5c97-a6fb-4ccb-b7df-be6dcfee9c43&book=64&par=2103)

**Comment by visuddhinanda** [comment]
已经修复
