### ISSUE TITLE
🐛切换版本时会强制改为阅读模式

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1821]
在[翻译模式下](https://next.wikipali.org/pcd/article/chapter/169-322?mode=edit&channel=1cb605eb-e144-488c-be16-cebb7c0f7255)选择版本风格
![Image](https://github.com/iapt-platform/mint/assets/84234053/07801b93-fd0d-4f4d-a7df-5460180b8144)

点击跳转后，链接中丢失了`mode=edit`参数

**Comment by visuddhinanda** [comment]
已经修复
