### ISSUE TITLE
🐛从问题链接跳转到原文会丢失channel信息

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#1883]
![Image](https://github.com/iapt-platform/mint/assets/84234053/c169b187-6881-43e3-b851-c2c69b89194a)
[问题链接](https://next.wikipali.org/pcd/discussion/topic/93ece136-a7cf-11ee-b0a3-0fc7f2fa650a)

**Comment by bhikkhu-kosalla-china** [comment]
跳转后


![Image](https://github.com/iapt-platform/mint/assets/84234053/c12c3d62-4f8f-4983-b5aa-f70c7a43a540)

**Comment by visuddhinanda** [comment]
已经修复
