### ISSUE TITLE
开发规范

### ISSUE THREAD

**Issue by wikipali** [iapt-platform/mint#2]
- 遵循git pull request 流程
- 所有代码必须经过格式化
- 禁止提交测试中间数据、key、db等文件
- Git commit message格式
  - 每条message不超过一行
  - 每个commit应该是独立的一个issue任务
  - message格式 `:code: message body`
  - code定义
    - bug fix: `:bug:`
    - new feature: `:construction:`
    - document: `:pencil:`
    - ops: `:rocket:`
    - config file: `:wrench:`
    - test case: `::white_check_mark:`

**Comment by visuddhinanda** [comment]
# issue 标签使用指南

标签应包含两个部分 issue类别和紧急程度

## 类别

- document(文档)-说明性的内容 如开发规范
- function(功能)-新功能需求或现有功能改进
- bug - bug修改
- art - 界面美化

## priority 紧急成度
- exigency 紧急 - 1-3 day
- normal - 一周内完成 within one week
- 不紧急 可以超过一个月
