### ISSUE TITLE
🐛 点词查询导致单词本未保存数据丢失

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#2006]
https://github.com/iapt-platform/mint/assets/84234053/5624ba96-dcb0-4ecd-a846-11b65c7ba03f

**Comment by visuddhinanda** [comment]
已经修复

![image](https://github.com/iapt-platform/mint/assets/63999293/3eb2b7ff-0100-4109-835f-d8f0c97cae9b)
