### ISSUE TITLE
数据库迁移

### ISSUE THREAD

**Issue by VitoVan** [iapt-platform/mint#457]
任务描述：

从 SQLite 迁移到 PostgreSQL

任务拆分：

- [x] 迁移方案规划
- [x] 读写频繁
- [ ] 写频繁，读不频繁
- [ ] 读频繁，写不频繁
- [ ] 不常用

**Comment by VitoVan** [comment]
@visuddhinanda 这个应该也是完成了的吧？

**Comment by visuddhinanda** [comment]
已经做了一多半。今天语料库pg 版已经上线。这周末部分用户数据pg 版上线。

Vito Van ***@***.***>于2021年12月29日 周三上午8:58写道：
