### ISSUE TITLE
词典模块重构

### ISSUE THREAD

**Issue by VitoVan** [iapt-platform/mint#460]
任务描述：

- [ ] 待补充任务描述

任务拆分：

- [ ] 待拆分任务

任务依赖： #457

**Comment by visuddhinanda** [comment]
https://stackoverflow.com/questions/tagged/ssh%2bphp?tab=Newest

带有升降按钮的界面

![Image](https://user-images.githubusercontent.com/63999293/172375573-39dfdc55-06ab-44eb-9c96-2e1af86f3f58.png)

**Comment by tanbw** [comment]
是指对词条加入点赞功能吗

**Comment by visuddhinanda** [comment]
> 是指对词条加入点赞功能吗

是的
