### ISSUE TITLE
用户逐词译字典支持删除

### ISSUE THREAD

**Issue by visuddhinanda** [iapt-platform/mint#549]
在译经楼用户字典模块删除记录。并更新引用计数。引用计数为零的彻底删除数据。

**Comment by visuddhinanda** [comment]
已经实现删除

**Comment by bhikkhu-kosalla-china** [comment]
最新版发现:bug:
删除之后会显示已删除的弹窗，但内容还在，仍然可以查询到。

**Comment by bhikkhu-kosalla-china** [comment]
另外，属于百科的删除也不行

**Comment by visuddhinanda** [comment]
测试请求：
在 https://staging.wikipali.org/ 上测试删除用户字典

![image](https://user-images.githubusercontent.com/63999293/182017649-9aadc082-9d56-4710-8d48-7a08f41d02cf.png)

显示这个说明成功
