### ISSUE TITLE
注释书展开的译文中的气泡无法出现

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#862]

**Comment by visuddhinanda** [comment]
已经改好。需要在staging 上测试

**Comment by bhikkhu-kosalla-china** [comment]
> 已经改好。需要在staging 上测试

已经测试，可用

**Comment by bhikkhu-kosalla-china** [comment]
![image](https://user-images.githubusercontent.com/84234053/175518764-01abf3a4-e66d-4fce-b7d3-f5022c0f72f7.png)

展开**注释**后，里面的PR✋按钮无法显示

**Comment by bhikkhu-kosalla-china** [comment]
在nissaya中，鼠标移入文字区块也无法弹出编辑气泡。

**Comment by bhikkhu-kosalla-china** [comment]
![image](https://user-images.githubusercontent.com/84234053/175555752-6b20216a-b2e0-4542-a07d-b998fff10eb0.png)

已提交过的PR再次修改显示
