### ISSUE TITLE
术语百科呈现界面无法编辑

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#863]
新增翻译模式之后，能够提升阅读体验，并刺激编辑者贡献译文。

**Comment by bhikkhu-kosalla-china** [comment]
新增翻译模式之后，能够提升阅读体验，并刺激编辑者贡献译文。

**Comment by visuddhinanda** [comment]
我想了一个解决方案：
在术语页面加一个翻译按钮。按了之后打开article . 从服务器取得一个由服务器生成的markdown文档。里面包含句子链接。就可以使用article的所有翻译功能。避免在术语页面做重复功能。

**Comment by bhikkhu-kosalla-china** [comment]
我觉得可行

**Comment by visuddhinanda** [comment]
已经改好。需要在staging 上测试
