### ISSUE TITLE
每日贡献统计表

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#867]
在贡献列表中，鼠标移入channel，能够得到文章每日贡献图表。
- y轴需增加自适应
- 统计数据按巴利字符计
![](https://www-hk.wikipali.org/api/sentence/progress/daily/image?view=page&book=65&from=830&to=906&channel=7ac4d13b-a43d-4409-91b5-5f2a82b916b3&text=21111)

按钮位置

![Image](https://user-images.githubusercontent.com/84234053/172389149-52168066-c559-43d2-8011-1ccf33389bb0.png)

**Comment by visuddhinanda** [comment]
测试链接：
https://staging.wikipali.org/app/article/index.php?view=chapter&book=107&par=2356&channal=7fea264d-7a26-40f8-bef7-bc95102760fb&display=para&mode=read&direction=row
channel进度图测试页面 
测试方法
点击按钮


![Image](https://user-images.githubusercontent.com/63999293/172747618-95a6f8b9-9daf-4fd3-be2a-da6f693a5ecb.png)

成功：
弹出进度图窗口
失败: 没反应，或窗口里没有内容
