### ISSUE TITLE
PR操作的bug

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#956]
自己在提交修改意见之后，自己不能采纳；
![image](https://user-images.githubusercontent.com/84234053/181728660-8fb3af75-da25-48df-9aab-1fe690948710.png)
这一点如果不修复，有修改权限的用户就会想要绕开PR直接修改。从而无法留下修改痕迹。

**Comment by visuddhinanda** [comment]
你在github上提交了pr.你自己可以merge吗？
如果你的管理模式是一定要提交pr那就别给这个人修改权限。
即使他采纳自己的。也会在时间线里留下历史记录。

**Comment by visuddhinanda** [comment]
如果一定要给某人修改权限。此人又一定需要提交修改建议。那么这个人就是双重身份。用管理手段解决比较好。跟他说好。别直接修改修行了。如果这个都不能遵守，想要故意绕过的人，你还要给他修改权限吗？

**Comment by visuddhinanda** [comment]
你的意思是：目前用户无法采纳自己的修改建议对吗？

**Comment by visuddhinanda** [comment]
改好了。在staging上测试一下
![屏幕截图 2022-07-29 201926.png](https://user-images.githubusercontent.com/63999293/181776426-82bfce31-703f-4292-8d28-318d4d4b75fd.png)
