### ISSUE TITLE
🐛 句子链接点击问题

### ISSUE THREAD

**Issue by bhikkhu-kosalla-china** [iapt-platform/mint#992]
当点击这个句子链接时
![image](https://user-images.githubusercontent.com/84234053/186465879-48747264-4426-4fad-abdf-addcc43404ee.png)
会打开好多页面
![image](https://user-images.githubusercontent.com/84234053/186465793-b60e5044-b628-4967-bb03-c1e2602b863b.png)
之前遇到过两个的，这么多还是第一次
并不是所有的句子都有
[测试链接](https://www-hk.wikipali.org/app/article/index.php?view=para&book=64&par=1669&channal=9659aefd-11df-42c5-9ae8-08813b2f2b44,40b9f2e6-cfcd-4e18-809b-3375e75ef88b&display=sent&mode=edit&direction=row)
问题句子：64-1669-2-12

而且，在不展开注疏的时候没有这样的问题，只有展开注疏之后，有这样的问题。
展开的注疏越多，问题越严重。
疑似jquery的简易函数的事件响应的问题。

**Comment by visuddhinanda** [comment]
从打开页面的次数可以知道你展开折叠注疏的次数。
